import Link from 'next/link'
import './globals.css'
import { Inter, Roboto, Lato } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['900'] })

export const metadata = {
  title: 'Angel Maden',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <nav>
            <Link href="/about">about</Link>
        </nav>
        {children}
        </body>
    </html>
  )
}
